### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by mkeeter**

### CODE REVIEW

**Review by leftwo — APPROVED** [review]
I thought these were fixed in some other PR, but I guess not..

**Comment by mkeeter** [comment]
Yeah, they're fixed in https://github.com/oxidecomputer/crucible/pull/1215 but it's a bit stalled, and I'm tired of seeing squiggly warnings in my editor.

**Review by jmpesp — APPROVED** [review]

**Comment by jmpesp** [comment]
I'm rebasing #1215 now but I'm not sure it matters which PR goes in first? :1st_place_medal:

**Comment by mkeeter** [comment]
oops, I must have forgotten to hit merge on this one

**Pull request merged**
