### PR TITLE
Reuse a reqwest client when creating repair client

### PR DESCRIPTION
**Pull request by jmpesp**
Similar to #1317, create a reqwest client once, and clone it when creating progenitor clients.

### CODE REVIEW

**Review by mkeeter — APPROVED** [review]

**Comment by leftwo** [comment]
Just to be sure, this will re-use the part of a client independent of where it's connecting to, right?  Like I don't
want my current repair to connect to the previous downstairs I repaired from, as that may not be the same as
the current downstairs I need to repair from.

**Comment by jmpesp** [comment]
> Just to be sure, this will re-use the part of a client independent of where it's connecting to, right? Like I don't want my current repair to connect to the previous downstairs I repaired from, as that may not be the same as the current downstairs I need to repair from.

Right - the repair (progenitor) client is what is passed the address of what downstairs to connect to, which is at a higher level than the reqwest client it's reusing.

**Comment by leftwo** [comment]
I fixed the problem with the live repair test (that my PR never seemed to hit), so if you merge main into this
it should run clean.  Even if not, the failures reported are due to log files changing after the test completed
so we can safely ignore the failure.

**Comment by jmpesp** [comment]
Taking this advice, merged in main.

**Pull request merged**
