### PR TITLE
Parallel flush in the downstairs

### PR DESCRIPTION
**Pull request by leftwo**
Use rayon to parallelize the region flush.

### CODE REVIEW

**Comment by leftwo** [comment]
All tests on Atrium

With parallel flush:
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
 rwrites   52.14  7000    1  134.27 0.00745 0.01821 0.03005  3.28592  4096  6400
 rwrites   29.04  7000    1  241.06 0.00415 0.00395 0.00718  1.63626  4096  6400
 rwrites   37.52  7000    1  186.58 0.00536 0.00441 0.04658  7.13240  8192  3200
 rwrites   28.40  7000    1  246.45 0.00406 0.00344 0.01593  3.03302  8192  3200

    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
  rreads    5.46  7000    1 1280.97 0.00078 0.00178 0.00324  0.03543  4096  6400
  rreads    5.12  7000    1 1367.24 0.00076 0.00151 0.00299  0.03543  4096  6400
  rreads    4.76  7000    1 1469.31 0.00068 0.00166 0.00204  0.01998  8192  3200
  rreads    5.13  7000    1 1365.77 0.00071 0.00176 0.00243  0.02660  8192  3200
```

crudd with parallel flush:
```
{ "request_size": 4096, "pipeline_length": 8, "read_speed_uninit": 107374182, "write_speed_uninit": 76695844, "read_speed_init": 89478485, "write_speed_init": 41698711 }
```

Without parallel flush:
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
 rwrites  152.87  7000    1   45.79 0.02184 0.01813 0.03495 17.83867  4096  6400
 rwrites   90.59  7000    1   77.27 0.01294 0.00475 0.00742 12.55055  4096  6400
 rwrites   78.93  7000    1   88.68 0.01128 0.00521 0.00651 24.58143  8192  3200
 rwrites   68.34  7000    1  102.43 0.00976 0.00417 0.00583  9.32160  8192  3200

    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
  rreads    4.63  7000    1 1513.34 0.00066 0.00114 0.00201  0.04715  4096  6400
  rreads    5.04  7000    1 1388.23 0.00069 0.00133 0.00226  0.04829  4096  6400
  rreads    4.43  7000    1 1579.97 0.00063 0.00107 0.00199  0.02407  8192  3200
  rreads    5.00  7000    1 1400.79 0.00067 0.00131 0.00237  0.02560  8192  3200
```

crudd without parallel flush:
```
{ "request_size": 4096, "pipeline_length": 8, "read_speed_uninit": 95443717, "write_speed_uninit": 57266230, "read_speed_init": 89478485, "write_speed_init": 43826196 }

real    6m4.738s
user    8m32.573s
sys     2m33.840s
```

**Comment by leftwo** [comment]
The big thing I notice about the test_perf.sh results is that the "MAX" value for random writes goes way down.
On the parallel flush, the largest max is 7 seconds (which is still way to high BTW), whereas on the non-parallel flush, the largest max is 24 seconds.

**Comment by faithanalog** [comment]
does upstairs still push periodic flush commands out even when no data has been written? if so I could maybe see downstairs acquiring locks on a lot of extents at once, leading to more of the reads getting stalled by a pending flush

**Comment by leftwo** [comment]
> does upstairs still push periodic flush commands out even when no data has been written? if so I could maybe see parallel flushes acquiring locks on a lot of extents at once, so reads have a higher chance getting stalled by a pending flush

Yes, the upstairs will send a flush even if there is no outstanding writes.  The upstairs uses the flush to clear internal upstairs work queues.  The logic could be smarter upstairs, but it's not currently.

**Comment by leftwo** [comment]
This change can put a large stress on free memory.  The current flush code path will read in the entire extent to re-compute the checksum for each block, and if we are doing that in parallel, it's `extent_size` * `block_size` * Number of "threads" that rayon creates.  With our largish extents, this can be a sizable chunk of memory.

**Comment by leftwo** [comment]
I'm going to hold this till after https://github.com/oxidecomputer/crucible/pull/576 goes in, as that should decrease the memory load to an acceptable level.

**Comment by leftwo** [comment]
This will have to be re-thought.
With the new `.async` nature of the extent flush operation, rayon may not be the best choice here.

**Comment by faithanalog** [comment]
i think an approach that might work is to tokio::spawn() a flush for each extent. that'll add all the flushes to the tokio job queue which will execute them with parallelism as the number of worker threads permits. and then you can join them all to wait for them to finish before returning from the flush command.

**Comment by jmpesp** [comment]
> i think an approach that might work is to tokio::spawn() a flush for each extent. that'll add all the flushes to the tokio job queue which will execute them with parallelism as the number of worker threads permits. and then you can join them all to wait for them to finish before returning from the flush command.

note that https://github.com/oxidecomputer/crucible/pull/659 does this

**Comment by leftwo** [comment]
Yeah, I had this open just to keep the idea around, but as this work has moved to other PRs, It's time to close it.

**Pull request closed without merging**
