### PR TITLE
Reduce Rayon pool size for Crucible Downstairs

### PR DESCRIPTION
**Pull request by mkeeter**
The Downstairs equivalent to #1294, but even simpler.

### CODE REVIEW

**Review by leftwo — COMMENTED** [review]
The changes look all good.
Do we have any perf numbers for this to see if it has any impact?
With all the other changes flowing in at the moment, it might make
sense to just merge them all and then run another pass and see
how we are and fine tune as necessayr.

**Comment by mkeeter** [comment]
Doing a sweep with `crutest rand-write`, it looks _very slightly_ worse than `main`.

I suspect that saving 120 threads a' spinning is still probably it, especially for heavily-loaded systems.

Screenshot 2024-05-15 at 1 25 39 PM

**Review by faithanalog — APPROVED** [review]
all my homies hate contention. we don't need rayon at all downstairs once we get the FIOFFS-equivalent working for flush right? or do we rayon the reads and writes too?

**Review by leftwo — APPROVED** [review]

**Comment by mkeeter** [comment]
> all my homies hate contention. we don't need rayon at all downstairs once we get the FIOFFS-equivalent working for flush right? or do we rayon the reads and writes too?

Correct, although it _may_ stick around for the non-illumos systems?

(now that I say that, I'm questioning whether it's necessary, since our performance/complexity tradeoff curve is different on non-Gimlet hardware...)

**Pull request merged**
