### PR TITLE
Make a crucible-client-types crate

### PR DESCRIPTION
**Pull request by leftwo**
This crate will allow omicron (and others who wish it) to
import just a few structures that Crucible uses, without having
to import (and build) all of Crucible.

### CODE REVIEW

**Comment by jclulow** [comment]
Perhaps `crucible-client-types` ?

**Comment by leftwo** [comment]
> Perhaps `crucible-client-types` ?

Yeah, that seems nicer.

**Comment by leftwo** [comment]
In a test build using this branch for omicron, I verified that [crucible] no longer shows up in the build process for omicron:

```
alan@atrium:omicron$ cargo build > /tmp/fff 2>&1                                                
alan@atrium:omicron$ grep crucible /tmp/fff                                     
   Compiling crucible-client-types v0.1.0 (https://github.com/oxidecomputer/cruc
ible?branch=clientlib#6f3fe5c9)                                                 
   Compiling crucible-agent-client v0.0.1 (https://github.com/oxidecomputer/cruc
ible?branch=clientlib#6f3fe5c9)                                                 
alan@atrium:omicron$
```

On a stock build: 
```
alan@atrium:ostock$ grep crucible /tmp/fffstock 
   Compiling crucible v0.0.1 (https://github.com/oxidecomputer/crucible?rev=2add0de8489f1d4de901bfe98fc28b0a6efcc3ea#2add0de8)
   Compiling crucible-common v0.0.0 (https://github.com/oxidecomputer/crucible?rev=2add0de8489f1d4de901bfe98fc28b0a6efcc3ea#2add0de8)
   Compiling crucible-protocol v0.0.0 (https://github.com/oxidecomputer/crucible?rev=2add0de8489f1d4de901bfe98fc28b0a6efcc3ea#2add0de8)
   Compiling crucible-agent-client v0.0.1 (https://github.com/oxidecomputer/crucible?rev=2add0de8489f1d4de901bfe98fc28b0a6efcc3ea#2add0de8)
```

The test build also contains fewer doc warnings than the stock build:
```
alan@atrium:omicron$ RUSTDOCFLAGS="-Dwarnings" cargo doc --workspace
warning: output filename collision.
The bin target `oximeter` in package `oximeter-collector v0.1.0 (/home/alan/ws/omicron/oximeter/collector)` has the same output filename as the lib target `oximeter` in package `oximeter v0.1.0 (/home/alan/ws/omicron/oximeter/oximeter)`.
Colliding filename is: /home/alan/ws/omicron/target/doc/oximeter/index.html
The targets should have unique names.
This is a known bug where multiple crates with the same name use
the same path; see <https://github.com/rust-lang/cargo/issues/6313>.
```

**Comment by leftwo** [comment]
Once this is approved and goes back, I'll make PRs for Propolis, then Omicron

**Comment by leftwo** [comment]
https://github.com/oxidecomputer/omicron/issues/1537

**Review by smklein — APPROVED** [review]
Thank you for building this!

**Comment by andrewjstone** [comment]
Woot!

**Review by jmpesp — APPROVED** [review]

**Pull request merged**
