### PR TITLE
Use `oneshot` channels instead of `mpsc` for notification

### PR DESCRIPTION
**Pull request by mkeeter**
Notifications from a `BlockReq` to a `BlockReqWaiter` are a single `Result<(), CrucibleError` message.  Right now, we're using `tokio::sync::mpsc::channel(1)`.  This  adds a sync point during `send` (because from the APIs perspective, the channel may be full, so `send` must be async).

Because we're only ever sending a single value through this channel, we can instead use a `tokio::sync::oneshot` channel, which is designed for this use case.

This is a small but statistically significant improvement on read IOPS (> 2 stdev change when running `crutest` 10x), and a small but statistically insignificant improvement for write speed (which has much higher variance).

### `main`
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
  rreads    6.55 30000    1 4583.10 0.00022 0.00025 0.00029  0.01471 16384   640
  rreads    6.46 30000    1 4646.06 0.00022 0.00025 0.00028  0.01525 16384   640
  rreads    6.51 30000    1 4608.56 0.00022 0.00025 0.00028  0.01525 16384   640
  rreads    6.52 30000    1 4603.10 0.00022 0.00025 0.00029  0.01525 16384   640
  rreads    6.51 30000    1 4607.41 0.00022 0.00025 0.00028  0.01562 16384   640
  rreads    6.49 30000    1 4620.88 0.00022 0.00025 0.00028  0.01562 16384   640
  rreads    6.51 30000    1 4607.92 0.00022 0.00025 0.00028  0.01562 16384   640
  rreads    6.49 30000    1 4621.01 0.00022 0.00025 0.00028  0.01562 16384   640
  rreads    6.48 30000    1 4632.23 0.00022 0.00025 0.00028  0.01562 16384   640
  rreads    6.51 30000    1 4610.36 0.00022 0.00025 0.00028  0.01562 16384   640
  IOPS: 4614 ± 16.3
  rreads    6.64 30000    1 4514.81 0.00022 0.00026 0.00030  0.01471 16384  1280
  rreads    6.52 30000    1 4599.36 0.00022 0.00025 0.00029  0.01471 16384  1280
  rreads    6.52 30000    1 4600.90 0.00022 0.00025 0.00029  0.01471 16384  1280
  rreads    6.52 30000    1 4597.74 0.00022 0.00025 0.00029  0.01471 16384  1280
  rreads    6.54 30000    1 4586.79 0.00022 0.00025 0.00029  0.01516 16384  1280
  rreads    6.53 30000    1 4593.17 0.00022 0.00025 0.00028  0.01534 16384  1280
  rreads    6.58 30000    1 4560.66 0.00022 0.00025 0.00028  0.01534 16384  1280
  rreads    6.55 30000    1 4581.24 0.00022 0.00025 0.00028  0.01563 16384  1280
  rreads    6.57 30000    1 4565.13 0.00022 0.00025 0.00028  0.01563 16384  1280
  rreads    6.52 30000    1 4601.92 0.00022 0.00025 0.00028  0.01563 16384  1280
  IOPS: 4580 ± 25.8
```
### `use-oneshot-channels`
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
  rreads    6.50 30000    1 4617.65 0.00022 0.00025 0.00029  0.01503 16384   640
  rreads    6.43 30000    1 4669.15 0.00022 0.00025 0.00029  0.01563 16384   640
  rreads    6.45 30000    1 4652.06 0.00022 0.00025 0.00028  0.01563 16384   640
  rreads    6.44 30000    1 4658.43 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.44 30000    1 4660.41 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.43 30000    1 4662.25 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.43 30000    1 4668.85 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.43 30000    1 4668.34 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.43 30000    1 4665.86 0.00021 0.00025 0.00028  0.01563 16384   640
  rreads    6.44 30000    1 4658.88 0.00021 0.00025 0.00028  0.01563 16384   640
  IOPS: 4658 ± 14.5
  rreads    6.55 30000    1 4582.55 0.00022 0.00025 0.00029  0.01474 16384  1280
  rreads    6.42 30000    1 4670.73 0.00022 0.00025 0.00029  0.01474 16384  1280
  rreads    6.45 30000    1 4649.84 0.00022 0.00025 0.00028  0.01474 16384  1280
  rreads    6.50 30000    1 4614.15 0.00022 0.00025 0.00028  0.01474 16384  1280
  rreads    6.47 30000    1 4634.51 0.00022 0.00025 0.00028  0.01518 16384  1280
  rreads    6.48 30000    1 4632.67 0.00022 0.00025 0.00028  0.01518 16384  1280
  rreads    6.45 30000    1 4654.31 0.00022 0.00025 0.00028  0.01518 16384  1280
  rreads    6.46 30000    1 4641.43 0.00022 0.00025 0.00028  0.01518 16384  1280
  rreads    6.45 30000    1 4652.11 0.00022 0.00025 0.00028  0.01529 16384  1280
  rreads    6.47 30000    1 4636.72 0.00022 0.00025 0.00028  0.01559 16384  1280
  IOPS: 4636 ± 23.2
```

### `main`
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
 rwrites    7.10 30000    1 4227.72 0.00024 0.00032 0.00067  0.01331 16384   640
 rwrites    6.89 30000    1 4355.05 0.00023 0.00031 0.00066  0.01631 16384   640
 rwrites    6.85 30000    1 4377.51 0.00023 0.00030 0.00056  0.01824 16384   640
 rwrites    6.92 30000    1 4332.38 0.00023 0.00031 0.00060  0.01436 16384   640
 rwrites    6.87 30000    1 4366.58 0.00023 0.00031 0.00069  0.01503 16384   640
 rwrites    6.97 30000    1 4303.62 0.00023 0.00031 0.00069  0.01445 16384   640
 rwrites    7.09 30000    1 4231.12 0.00024 0.00032 0.00068  0.01692 16384   640
 rwrites    7.05 30000    1 4253.96 0.00023 0.00031 0.00068  0.01424 16384   640
 rwrites    7.06 30000    1 4250.98 0.00024 0.00032 0.00067  0.01822 16384   640
 rwrites    7.14 30000    1 4198.80 0.00024 0.00032 0.00061  0.01515 16384   640
 IOPS: 4289 ± 61.8
 rwrites    7.56 30000    1 3967.94 0.00025 0.00035 0.00080  0.01308 16384  1280
 rwrites    7.47 30000    1 4014.44 0.00025 0.00035 0.00090  0.01793 16384  1280
 rwrites    7.41 30000    1 4048.19 0.00025 0.00033 0.00078  0.01511 16384  1280
 rwrites    7.56 30000    1 3967.28 0.00025 0.00035 0.00086  0.01492 16384  1280
 rwrites    7.65 30000    1 3923.07 0.00025 0.00035 0.00084  0.01692 16384  1280
 rwrites    7.59 30000    1 3953.03 0.00025 0.00036 0.00087  0.01494 16384  1280
 rwrites    7.65 30000    1 3923.95 0.00025 0.00036 0.00084  0.02104 16384  1280
 rwrites    7.62 30000    1 3939.42 0.00025 0.00034 0.00079  0.01837 16384  1280
 rwrites    7.58 30000    1 3955.26 0.00025 0.00035 0.00083  0.02386 16384  1280
 rwrites    7.79 30000    1 3850.71 0.00026 0.00037 0.00091  0.01399 16384  1280
 IOPS: 3954 ± 50.6
 ```
 
### `use-oneshot-channels`
```
    TEST SECONDS COUNT DPTH    IOPS    MEAN     P95     P99      MAX    ES    EC
 rwrites    6.84 30000    1 4387.68 0.00023 0.00031 0.00060  0.01490 16384   640
 rwrites    6.76 30000    1 4439.42 0.00023 0.00031 0.00064  0.02136 16384   640
 rwrites    6.71 30000    1 4470.80 0.00022 0.00030 0.00063  0.01495 16384   640
 rwrites    6.87 30000    1 4365.02 0.00023 0.00031 0.00063  0.01553 16384   640
 rwrites    6.98 30000    1 4298.77 0.00023 0.00032 0.00071  0.01379 16384   640
 rwrites    6.91 30000    1 4338.87 0.00023 0.00031 0.00065  0.01949 16384   640
 rwrites    6.94 30000    1 4321.55 0.00023 0.00032 0.00066  0.01771 16384   640
 rwrites    6.96 30000    1 4310.83 0.00023 0.00032 0.00062  0.01384 16384   640
 rwrites    6.95 30000    1 4316.72 0.00023 0.00032 0.00059  0.01501 16384   640
 rwrites    7.17 30000    1 4182.85 0.00024 0.00032 0.00056  0.02147 16384   640
 IOPS: 4343 ± 76.1
 rwrites    7.44 30000    1 4030.18 0.00025 0.00035 0.00080  0.01301 16384  1280
 rwrites    7.37 30000    1 4069.49 0.00025 0.00033 0.00079  0.01766 16384  1280
 rwrites    7.50 30000    1 4000.72 0.00025 0.00034 0.00083  0.01800 16384  1280
 rwrites    7.50 30000    1 3999.46 0.00025 0.00033 0.00078  0.01748 16384  1280
 rwrites    7.49 30000    1 4006.84 0.00025 0.00035 0.00085  0.02014 16384  1280
 rwrites    7.52 30000    1 3986.80 0.00025 0.00035 0.00087  0.01885 16384  1280
 rwrites    7.53 30000    1 3986.03 0.00025 0.00035 0.00085  0.01559 16384  1280
 rwrites    7.56 30000    1 3968.88 0.00025 0.00035 0.00088  0.01416 16384  1280
 rwrites    7.64 30000    1 3926.24 0.00025 0.00036 0.00088  0.01641 16384  1280
 rwrites    7.63 30000    1 3932.45 0.00025 0.00034 0.00089  0.02201 16384  1280
 IOPS: 3990 ± 40.3
```

### CODE REVIEW

**Review by jmpesp — APPROVED** [review]

**Review by leftwo — APPROVED** [review]
This seems pretty straight forward.  Probably a few other places where we can
do a similar thing.

**Review by faithanalog — APPROVED** [review]

**Comment by leftwo** [comment]
I went through this a few times and I can't see any way this change could have resulted in the CI failure we saw
with it before. 🤷

**Comment by leftwo** [comment]
Oooo.. I think I figured out how that CI failure could have happened, and it does not have anything
to do with this change, so, yeah, that's.. good I guess :)

**Comment by mkeeter** [comment]
Heck yeah, let's get this merged

**Pull request merged**
